# Generated by Django 6.0.7 on 2026-08-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'verbose_name': 'editor', 'verbose_name_plural': 'editors'},
        ),
    ]
